# Generated by Django 4.2 on 2023-04-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
    ]
